### PR TITLE
Fix external name configuration for ECS Service

### LINKED ISSUE #170: ECS Service: cannot set external name
### What happened?

When creating an ECS service, the provider cannot set the external-name annotation. 

```
 Warning  CannotObserveExternalResource  4m47s (x918 over 78m)  managed/ecs.aws.jet.crossplane.io/v1alpha2, kind=service  cannot set critical annotations: cannot get external name: external name should have the following format: cluster-name/service-name
```

It looks like it is omitting the cluster name from the external name:

```yaml 
             crossplane.io/external-name: xppoca1-ecs-prq7x
```

### How can we reproduce it?

```yaml
Name:         xppoca1-ecs-prq7x
Namespace:    
Labels:       crossplane.io/claim-name=
              crossplane.io/claim-namespace=
              crossplane.io/composite=xppoca1-ecs
Annotations:  crossplane.io/external-create-pending: 2022-03-11T16:45:42Z
              crossplane.io/external-create-succeeded: 2022-03-11T16:45:42Z
              crossplane.io/external-name: xppoca1-ecs-prq7x
API Version:  ecs.aws.jet.crossplane.io/v1alpha2
Kind:         Service
Metadata:
  Creation Timestamp:  2022-03-11T16:44:29Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generate Name:  xppoca1-ecs-
  Generation:     3
  Managed Fields:
    API Version:  ecs.aws.jet.crossplane.io/v1alpha2
    Manager:      crossplane
    Operation:    Update
    Time:         2022-03-11T16:45:15Z
    API Version:  ecs.aws.jet.crossplane.io/v1alpha2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:crossplane.io/external-create-pending:
          f:crossplane.io/external-create-succeeded:
          f:crossplane.io/external-name:
        f:finalizers:
          .:
          v:"finalizer.managedresource.crossplane.io":
      f:status:
        .:
        f:atProvider:
          .:
          f:id:
        f:conditions:
    Manager:    crossplane-provider
    Operation:  Update
    Time:       2022-03-11T16:45:53Z
  Owner References:
    API Version:     aws.autodemo.crossplane.io/v1alpha1
    Controller:      true
    Kind:            XECSCluster
    Name:            xppoca1-ecs
    UID:             86276eb4-f0f7-4142-a0d6-b8472d17ab2f
  Resource Version:  42829906
  UID:               639932b1-e0a9-46ee-bbb5-a642c866ea93
Spec:
  Deletion Policy:  Delete
  For Provider:
    Cluster:  xppoca1-ecs-snq6z
    Network Configuration:
      Subnets:
        subnet1
    Region:           us-west-2
    Task Definition:  demo-task1:3
  Provider Config Ref:
    Name:  aws-provider
Status:
  At Provider:
    Id:  arn:aws:ecs:us-west-2:ACCOUNT:service/test-ecs-snq6z/test-ecs-prq7x
  Conditions:
    Last Transition Time:  2022-03-11T16:45:53Z
    Message:               observe failed: cannot set critical annotations: cannot get external name: external name should have the following format: cluster-name/service-name
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
    Last Transition Time:  2022-03-11T16:44:38Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-03-11T16:45:48Z
    Reason:                Finished
    Status:                True
    Type:                  AsyncOperation
    Last Transition Time:  2022-03-11T16:45:48Z
    Reason:                Success
    Status:                True
    Type:                  LastAsyncOperation
```

### What environment did it happen in?

Crossplane version:  1.6.2
Provider-jet-aws: 0.4.0

### PR DESCRIPTION
**Pull request by turkenh**
### Description of your changes

This PR fixes ECS Service external name configuration and adds a working/tested example.

Fixes #170 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

Using the (renamed) example manifest which is also added in this PR.

```bash
kubectl get -f examples/ecs/service.yaml -w
NAME                      READY   SYNCED   EXTERNAL-NAME             AGE
sample-service-by-hasan                    sample-service-by-hasan   2s
sample-service-by-hasan                    sample-service-by-hasan   35s
sample-service-by-hasan                    sample-service-by-hasan   35s
sample-service-by-hasan                    sample-service-by-hasan   35s
sample-service-by-hasan   False   True     sample-service-by-hasan   35s
sample-service-by-hasan   False   True     sample-service-by-hasan   35s
sample-service-by-hasan   False   True     sample-service-by-hasan   59s
sample-service-by-hasan   False   True     sample-service-by-hasan   63s
sample-service-by-hasan   False   True     sample-service-by-hasan   63s
sample-service-by-hasan   True    True     sample-service-by-hasan   77s
sample-service-by-hasan   True    True     sample-service-by-hasan   111s
```

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by ulucinar — APPROVED** [review]

File: config/ecs/config.go [hunk 1]
```diff
@@ -50,10 +50,10 @@ func Configure(p *config.Provider) {
 		r.Version = common.VersionV1Alpha2
 		r.ExternalName = config.NameAsIdentifier
 		r.ExternalName.GetExternalNameFn = func(tfstate map[string]interface{}) (string, error) {
-			// cluster-name/service-name
+			// expected id format: arn:aws:ecs:us-east-2:123456789123:service/hasan-test/sample-service-by-hasan
 			w := strings.Split(tfstate["id"].(string), "/")
-			if len(w) != 2 {
-				return "", errors.New("external name should have the following format: cluster-name/service-name")
+			if len(w) != 3 {
+				return "", errors.New("terraform ID should be the ARN of the cluster")
```
Comment (ulucinar) [inline config/ecs/config.go:56]: nit:
```suggestion
				return "", errors.New("terraform ID should be the ARN of the service")
```
